update github account
engineer-365/idea-and-plan pull request #10
Opened 2020-12-08 03:51 UTC by zlmkenan

update github account

2020-12-09 03:51 UTC, CNYuYang reviewed
maven配置JDK版本的修改，不应该提交。

2020-12-09 04:24 UTC, qiangyt requested changes
> maven配置JDK版本的修改，不应该提交。

非常同意。每个PR有自己的主题，是JIRA等项目管理工具的参考，不应该混在一起。

2020-12-09 04:24 UTC, qiangyt commented on server/pom.xml
> +          <target>1.8</target>
根本就没打算支持1.8。
已经用到了不少11的语法。

2020-12-13 07:41 UTC, knoxnoe approved these changes, later dismissed

2020-12-18 06:05 UTC, zlmkenan commented
1 并没有去修改主的jdk版本，只是新增了一个插件去兼容低版本的jdk
2 受限于其他因素，不可能所有的开发者都会去升级jdk的版本，新增一个插件的做法，至少可以保证编译的正常进行。支持用新的语法开发，但也应允许向下兼容

2020-12-18 12:40 UTC, qiangyt commented
> 1 并没有去修改主的jdk版本，只是新增了一个插件去兼容低版本的jdk
> 2 受限于其他因素，不可能所有的开发者都会去升级jdk的版本，新增一个插件的做法，至少可以保证编译的正常进行。支持用新的语法开发，但也应允许向下兼容

source=1.8会导致代码中使用的新的语法的地方编译失败。

1.8已经很旧，而且oracle对1.8的支持是收费的，各方面原因，兼容java 1.8版本目前不是目标，类似对兼容性的处理是一个空间/余地。

另外，就像@CNYuYang所说，这个PR是参与和报名用，修改maven设置应该另提一个PR。另一个角度看，因为maven配置的争议，导致members.md不能被合并，也正说明了每个PR专注不同的事情的重要性。

2021-01-07 14:26 UTC, qiangyt commented on server/pom.xml
> +          <target>1.8</target>
Confirmed this is due to accidental commit. Revert it.

2021-01-07 14:26 UTC, qiangyt approved these changes

2021-01-07 14:28 UTC, merged